_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.3
            "8":
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
cache_path:
    value: ./data/cache/
cfg_file:
    value: KPDetection
data_dir:
    value: ./data
pretrained_model:
    value: KPDetection.pkl
start_iter:
    value: 0
threads:
    value: 1
